### ISSUE TITLE
Contents Buffer

### ISSUE THREAD

**Issue by dahmian** [Waxolunist/metalsmith-writemetadata#1]
Thanks for writing this plug in! I have a question about contents. I noticed that metalsmith outputs the "contents" as a buffer, so if I use this plugin, "contents" is not available to the JSON output. What if I want to use contents in the JSON file? Is there a way to do this without modifying metalsmith-writemetadata to output a string instead of a buffer?

**Comment by Waxolunist** [comment]
No it is not possible without modifying it. I can have a look, so maybe there is an option.

If you have problems using the buffer you can have a look into my site: http://christian.sterzl.info or https://github.com/Waxolunist/christian.sterzl.info

**Comment by Waxolunist** [comment]
Is this solution what you expected?

**Comment by dahmian** [comment]
Yes! That works just like I would expect.

**Comment by Waxolunist** [comment]
Cool. I had a small error. You should use 0.4.4.
